name: saju_app
description: Elemental Blueprint App
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

   # --- Firebase & Social Login (최신 버전으로 정렬) ---
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  google_sign_in: ^6.2.1

  # --- 기타 필수 ---
  http: ^1.2.1
  google_fonts: ^6.2.1
  provider: ^6.1.2
  intl: ^0.19.0
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # 이미지 폴더 등록
  assets:
    - assets/images/